import AuthSession from "@/components/providers/session-provider";
import LoginButton from "@/components/login-button";
import type { Metadata } from "next";
import localFont from "next/font/local";
// import Script from "next/script";
import "./globals.css";
import CustomMenu from "@/components/providers/CustomMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:w-[80%] sm:w-[100%] m-auto h-full`}
      >
        <AuthSession>
          <div className="h-[48px] flex items-center bg-[#FFB200] justify-between px-5">
            <div>
              <CustomMenu
                menuList={[
                  { key: "event", value: "이벤트 페이지" },
                  { key: "community", value: "소통 게시판" },
                  { key: "hotel", value: "반려동물 호텔 예약" },
                ]}
              />
            </div>
            <div className="font-bold">OH MY PET</div>
            <div>
              <LoginButton />
            </div>
          </div>
          {children}
        </AuthSession>
      </body>
    </html>
  );
}
